// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/index.tsx";
import * as $1 from "./pages/_render.ts";
import * as $2 from "./pages/api/login.ts";
import * as $3 from "./pages/[id].tsx";
import * as $4 from "./pages/api.tsx";
import * as $5 from "./pages/admin.tsx";
import * as $6 from "./pages/alias.tsx";

const routes = {
  pages: {
    "./pages/index.tsx": $0,
    "./pages/_render.ts": $1,
    "./pages/api/login.ts": $2,
    "./pages/[id].tsx": $3,
    "./pages/api.tsx": $4,
    "./pages/admin.tsx": $5,
    "./pages/alias.tsx": $6,
  },
  baseUrl: import.meta.url,
};

export default routes;
